services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tibi
      POSTGRES_PASSWORD: tibi
      POSTGRES_DB: open_workout
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
